### ISSUE TITLE
gem of tprov does not work

### ISSUE THREAD

**Issue by jasine** [jamtur01/dockerbook-code#11]
In 6.2.5 
The gem installed by command `sudo gem install -no-rdoc --no-ri tprov` does not work correctly, but the gem I built from the code here works well, the file  `app.rb` is different, it seems that you didn't update the gem on server.
![qq20150325-1 2x](https://cloud.githubusercontent.com/assets/1934966/6822363/158e149c-d31a-11e4-9040-4776956035f4.png)

Finally, in the Dockerfile of 6.2.1, the latest version of `wget` does not have the option `-?`, it should be '-h' .

**Comment by jamtur01** [comment]
The gem has been updated. I'll look at the wget option. Thanks for reporting the issues!
