### ISSUE TITLE
Code list 7-30 correction

### ISSUE THREAD

**Issue by thinkhy** [jamtur01/dockerbook-code#13]
The command below in Code list 7-30 doesn't work on my VM.

     PUBLIC_IP="$(ifconfig eth0 | awk -F ' *|:' '/inet addr/{print $4}')"

so I corrected it as following:

    PUBLIC_IP="$(ifconfig eth1 | awk -F ' *|:' '/inet/{print $3}')"

My OS is CentOS 7.1:

   [root@sv consul]# lsb_release -a
   LSB Version:    :core-4.1-amd64:core-4.1-noarch
   Distributor ID: CentOS
   Description:    CentOS Linux release 7.1.1503 (Core)
   Release:        7.1.1503
   Codename:       Core

**Comment by jamtur01** [comment]
Thanks - in the chapter the hosts are based on Ubuntu so that's why its the default there.
