### ISSUE TITLE
Error in Chapter 5 Jenkins Dockerfile

### ISSUE THREAD

**Issue by smclurkin** [jamtur01/dockerbook-code#14]
I received the following error when trying to build Jenkins in chapter 5.  

     "E: The method driver /usr/lib/apt/methods/http could not be found."

To fix this error I added the following to my build script:

    RUN apt-get -y install apt-transport-https

**Comment by jamtur01** [comment]
Thanks - this was fixed but I forgot to push it b38b69a2e6d9d7e7284bbb444ebb673888d5aee7.
