### ISSUE TITLE
Error in  Chapter 6 about jekyll container start

### ISSUE THREAD

**Issue by Baz2013** [jamtur01/dockerbook-code#25]
$docker run -v /home/docker/the_docker_book/jekyll/james_blog:/data/ \
@iZ25r06n0jfZ > --name james_blog jekyll
DEPRECATION WARNING:
Sass 3.5 will no longer support Ruby 1.9.3.
Please upgrade to Ruby 2.0.0 or greater as soon as possible.

Configuration file: /data/_config.yml
            Source: /data
       Destination: /var/www/html
      Generating... 
     Build Warning: Layout 'nil' requested in atom.xml does not exist.

I have no experience of ruby , anybody could tell me how to solve ?

**Comment by jamtur01** [comment]
This should now be fixed by updating the: `FROM ubuntu:14.04`to `FROM ubuntu:16.04`.
