### ISSUE TITLE
oci runtime error: exec: " nginx": executable file not found 

### ISSUE THREAD

**Issue by axyr** [jamtur01/dockerbook-code#33]
Docker Version 1.12.1 (build: 12133)
OSX Version 10.11.5 (15F34)

When running :

```
docker run -d -p 80 --name static_web jamtur01/static_web \ nginx -g "daemon off;"
```

As written on page 96 from Version: v1.12.2 (51305ad)

I get this message : 

```
docker: Error response from daemon: oci runtime error: exec: " nginx": executable file not found in $PATH.
```

I tried several variations, but no luck...

**Comment by jamtur01** [comment]
Try it without the \

docker run -d -p 80 --name static_web jamtur01/static_web nginx -g "daemon off;"

**Comment by Kalaikkovan** [comment]
starting container process caused "exec: \"-g\": executable file not found in $PATH": unknown
