### ISSUE TITLE
"Cannot connect to the Docker daemon" after restarting Jenkins docker container

### ISSUE THREAD

**Issue by grange74** [jamtur01/dockerbook-code#9]
While following along with section 6.3 "Using Docker for continuous integration" of the book, I setup and ran successfully both the Jenkins Freestyle task 'Docker_test_job' and the Multi-configuration task 'Docker_matrix_job'. 

I then stopped the container & restarted my mac. I then wanted to show a colleague so i started the Jenkins container but when i ran both tasks they started failing with ""Cannot connect to the Docker daemon. Is 'docker -d' running on this host?". 

I tried varies things but couldn't get around it apart from deleting the container and recreating it and resetting up Jenkins. The builds then worked fine. I stopped the container and started it again and again the builds started failing with the same message.

Now i'm not sure if this a user-error, Docker version (using 1.5), boot2docker (1.5.0) on OSX 10.10.2 or Docker-in-Docker problem or a combination. It seems that the Jenkins task can access the Docker client (i temporarily added `docker -v` to the shell script to check) but not the Docker daemon. Not sure why. It is probably not worth spending a lot of time investigating this but i thought i'd log it in case it somehow saved someone some time.

Here is the full console output from the Jenkins task:
```Started by user anonymous
Building in workspace /tmp/jenkins-buildenv/Docker_test_job/workspace
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/jamtur01/docker-jenkins-sample.git # timeout=10
Fetching upstream changes from https://github.com/jamtur01/docker-jenkins-sample.git
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/jamtur01/docker-jenkins-sample.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision e4830a7c4a17b2614aee8c158ecd5da434c4412c (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f e4830a7c4a17b2614aee8c158ecd5da434c4412c
 > git rev-list e4830a7c4a17b2614aee8c158ecd5da434c4412c # timeout=10
[workspace] $ /bin/sh -xe /tmp/hudson2769868839445177006.sh
+ docker build .
+ tail -1
+ awk { print $NF }
time="2015-02-23T22:35:52Z" level="fatal" msg="Cannot connect to the Docker daemon. Is 'docker -d' running on this host?" 
+ IMAGE=
+ MNT=/tmp/jenkins-buildenv/Docker_test_job/workspace/..
+ docker run -d -v /tmp/jenkins-buildenv/Docker_test_job/workspace/..:/opt/project 
 /bin/bash -c cd /opt/project/workspace && rake spec
time="2015-02-23T22:35:53Z" level="fatal" msg="Cannot connect to the Docker daemon. Is 'docker -d' running on this host?" 
+ CONTAINER=
Build step 'Execute shell' marked build as failure
Recording test results
Finished: FAILURE```

**Comment by grange74** [comment]
After doing some more searching, i think my issue may be related to the `docker start` command not supporting the privileged options which results in not having access to the host's docker daemon through `VOLUME /var/lib/docker` in the dockerfile.

There is already a feature request for this:
Feature request: -v and --privileged options for 'docker start' (https://github.com/docker/docker/issues/9343)

**Comment by jamtur01** [comment]
I think you're right. Thanks for reporting this.
